CREATE TABLE electricity_notifications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    region VARCHAR(255) NOT NULL,
    message VARCHAR(255) NOT NULL,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    category ENUM('BREAKDOWN', 'MAINTENANCE', 'OTHER') NOT NULL DEFAULT 'OTHER',
    sent_to VARCHAR(255) NOT NULL DEFAULT 'ALL'
);